### ISSUE TITLE
multinode_server import error

### ISSUE THREAD

**Issue by andreadistefano** [yarox/morseweb#18]
Hi!
I just started using MORSE today, so excuse me for my total noobness. I followed the [tutorial](https://www.openrobots.org/morse/doc/stable/headless.html) on MORSE website to get it to run in headless mode, and it seems to work, but when I try to run the multinode_server before starting the web interface I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/multinode_server", line 30, in <module>
    from pymorse.stream import StreamJSON, PollThread
ImportError: cannot import name 'PollThread'
```

Any idea how to fix it?
Thanks!

**Comment by yarox** [comment]
Hi! What version of MORSE are you running?

**Comment by andreadistefano** [comment]
I'm running 1.2 compiled from the MORSE git repository (following [these instructions](https://www.openrobots.org/morse/doc/stable/user/installation.html#installation)).

Here is the output of `morse check`

```
* Checking up your environment...


* Running on Linux. Alright.

* Found MORSE libraries in '/usr/lib/python3/dist-packages/morse/blender'. Alright.

* Trying to figure out a prefix from the script location...

* Default scene found. The prefix seems ok. Using it.

* Setting $MORSE_ROOT environment variable to default prefix [/usr/local/]

* Checking version of /usr/bin/blender... Found v.2.69.0

* Found Blender in your PATH
(/usr/bin/blender, v.2.69.0).
Alright, using it.

* Checking version of Python within Blender /usr/bin/blender... Found v.3.4.3

* Blender and Morse are using Python 3.4.3. Alright.

* Your environment is correctly setup to run MORSE.
```

**Comment by yarox** [comment]
I see. Version 1.2 is from 2014 and some Python modules in MORSE may have changed (hence the error). Current version (and the one supported by morseweb) is **1.4**. You can checkout the `1.4_STABLE` branch with this command:

```
$ git clone https://github.com/morse-simulator/morse.git -b 1.4_STABLE
```

Then, you can rebuild it and it should work just fine!

**Comment by andreadistefano** [comment]
I think I solved it, but when I tried building it from the branch you linked `morse -v` was still 1.2 and it still did not work.
Then, in a sudden moment of clarity, I uninstalled everything and reinstalled morse using `apt-get install morse-simulator` and now the multinode_server works. But `morse -v` is STILL 1.2.  

Thanks for your help!

**Comment by yarox** [comment]
That's great, but morseweb needs version **1.4** to work. The command I gave you works for cloning the repo for the first time. Try this for updating your existing MORSE installation:

```
$ git pull --rebase https://github.com/morse-simulator/morse.git master 
$ cd build
$ sudo make install
```

**Comment by andreadistefano** [comment]
Yeah, you are right, sorry about that (in fact I later got the same error about PollThread).
But still, even after removing every trace of MORSE from my system, when I checkout the `1.4_STABLE` branch and rebuild the project, I always get the 1.2 version. Now I'm going nuclear, I'm formatting the system and starting over (it was a fresh install, should not take too long).

I feel I already wasted too much of your time, I will give an update as soon as possible.

**Comment by yarox** [comment]
No problem! I got stuck several times too! Let me know how it went :smiley:
